services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zmstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zmstore"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/zmstore?schema=public
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma migrate deploy &&
             npm run start"

volumes:
  postgres_data:
