services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zmstore
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             npm run build &&
             npx remix-serve build/server/index.js"

volumes:
  postgres_data:
