ALTER TABLE "Order" DROP COLUMN IF EXISTS "deliverPhotoKey";

DROP TABLE IF EXISTS "OverrideLog" CASCADE;
DROP TABLE IF EXISTS "RunAdhocSale" CASCADE;
DROP TABLE IF EXISTS "CylinderLoan" CASCADE;
DROP TABLE IF EXISTS "SaleItem" CASCADE;
DROP TABLE IF EXISTS "Sale" CASCADE;

DROP TYPE IF EXISTS "OverrideKind";
